### ISSUE TITLE
How to generate the .list or pickle

### ISSUE THREAD

**Issue by Neroaway** [uniBruce/Mead#11]
Hi, thank you for this  great dataset.But when I want to train this work step by step,I find some problem.
(1) Audio2Landmark: 
     dataloader : how to generate audio_demo.list ?  where is ./lists/landmarks.pickle? Could you tell me how to generate these files? ie. in audio_demo.txt why it is 
"M003_07_1_output_01/000.pickle reference.jpg"? 
(2) video_list.txt:
   how to generate video_list?ie. in video_list.txt why it is "M003/M003_01_1_output_01/000.jpg"?
Could you realse the generate code?

**Comment by uniBruce** [comment]
This depends on how you set up the data structure. I used "M003_07_1_output_01/000.pickle reference.jpg" just because these data were collected in this way at the beginning of this project. M003 stands for the actor number, 07 stands for the folder number. Right now each sentence is separated, then you can try to construct a new structure as you like.

In terms of ''landmarks.pickle'', it must be the ''pca.pickle'' (I forgot to change the name, sorry about that). You can try to use the preprocess_ldmk.py in the directory.

**Comment by Neroaway** [comment]
Thank you!There is another problem： When I train the Audio2Landmark, the dataloader donot find the audio_list.txt and in your preprocess_ldmk.py use the mouth_ldmk.txt, but in the lists, I cannot find the mouth_ldmk.txt.`root = './lists/mouth_ldmk.txt'`, btw，If it is convenient, I hope I can contact you by email.

**Comment by uniBruce** [comment]
> Thank you!There is another problem： When I train the Audio2Landmark, the dataloader donot find the audio_list.txt and in your preprocess_ldmk.py use the mouth_ldmk.txt, but in the lists, I cannot find the mouth_ldmk.txt.`root = './lists/mouth_ldmk.txt'`, btw，If it is convenient, I hope I can contact you by email.

Hi, actually. The mouth_landmark is processed by an open-source method mentioned in the paper. You could refer to that to extract landmarks from the data.
